name: CI Workflow for Gym Membership Management System

on:
  # Opción 2: Disparar el workflow en pull requests a la rama main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Analizar el código con Flake8
      - name: Lint code with Flake8
        run: |
          pip install flake8
          flake8 .

      # Paso 5: Ejecutar pruebas con Pytest
      - name: Run tests
        run: |
          pytest
